### ISSUE TITLE
Possible dead project?

### ISSUE THREAD

**Issue by sethmlarson** [kmwhite/artisan#1]
Hello kmwhite,

I am currently creating a project and would like to use the name `artisan` on PyPI, seeing as this project hasn't had any updates in the past four years and there isn't anyone downloading the package from PyPI I came to ask if you would perhaps unpublish the module from PyPI so I may use the name? :)

If you decide not to it is okay, but I would be very appreciative if you were able to do this.
Thank you so much,

Seth Larson

**Comment by kmwhite** [comment]
Sure. I can unpublish. I didn't get the time I wanted to for working on this, so I am happy to release the name. :) Can I do it later today?

**Comment by sethmlarson** [comment]
You can do it whenever, thank you so much for taking time out of your schedule for this. :) Kudos to you! Just tweet at me or post here when you do.  Thanks again!!! :tada: :cake: :tada:

**Comment by kmwhite** [comment]
Released.
